### ISSUE TITLE
"Created by" text color adjustment for Dark Mode

### ISSUE THREAD

**Issue by muhammadhafijur** [muhammadhafijur/image-blender#10]
The task is to adjust the "Created by" text color to match the design standards for dark mode. The "Created by" color should be white color (you can use class like `text-gray-200` or `text-gray-300` class for this) by default in dark mode. 

![Screenshot 2024-10-06 183357](https://github.com/user-attachments/assets/09036895-4eca-4575-8a89-008a661fd7df)

**Comment by sujalcharati** [comment]
please can i be assigned

**Comment by muhammadhafijur** [comment]
> please can i be assigned

Assigned! Let me know if you need anything further.

**Comment by sujalcharati** [comment]
for sure..
