### ISSUE TITLE
Copy button margin is off

### ISSUE THREAD

**Issue by moo-light** [muhammadhafijur/image-blender#19]
Hey i want to fix the copy button padding issue 
![image](https://github.com/user-attachments/assets/6bbd1f31-37c6-43e1-bfc6-0d9fcaa0469e)
to this 
![image](https://github.com/user-attachments/assets/84eee29c-61d2-4257-8916-850a03075ff9)
please assign me this

**Comment by muhammadhafijur** [comment]
Sure. Make sure to pull the latest changes as well.

**Comment by muhammadhafijur** [comment]
Great work 🎉
