### ISSUE TITLE
Hero Section Placement and Scroll Button

### ISSUE THREAD

**Issue by clydehenry3** [muhammadhafijur/image-blender#2]
Description:
The hero section looks amazing, but it would have a greater impact if positioned above the photo editor. This would create a better sense of trust for users when they first land on the platform. It will also enhance the flow from the hero section to the statistics showing how many images have been made so far.

Enhancement Proposal:
Move the hero section to the top of the page, above the editor.
Add a button in the hero section that auto-scrolls users to the photo editor for a smoother UX.

Environment:
React
TailwindCSS

Let me know if you’d like help implementing the scroll button functionality!

**Comment by muhammadhafijur** [comment]
Hi @clydehenry3,

Thank you for your suggestion!

I appreciate the detailed feedback and enhancement proposal. I’ve taken some inspiration from the following websites:

[Restore Photos](https://www.restorephotos.io/)
[Heroicons](https://heroicons.com/)

For this project, I'm using Vuejs and Tailwindcss. If you could provide a low fidelity wireframe or any visual reference for your proposal about hero section, that would be a big help.

Also this is a good idea.
> Add a button in the hero section that auto-scrolls users to the photo editor for a smoother UX.

Best wishes!

**Comment by clydehenry3** [comment]
I can get a wireframe for you today. Also, could you assign this issue to me? 

Thank you!

**Comment by muhammadhafijur** [comment]
Sure. Looking forward to it.
