### ISSUE TITLE
Icon button hovering effect

### ISSUE THREAD

**Issue by moo-light** [muhammadhafijur/image-blender#20]
I want to change the Icon button hovering effect to make it more interactive
the first image is before hover
![image](https://github.com/user-attachments/assets/8ad6c428-ce61-4aed-a69d-0fed598a8d8f)
the second is after hover with background opacity shrink to 80% `hover:bg-opacity-80` (please ignore the differences in color)
![image](https://github.com/user-attachments/assets/ded647fd-89b0-455d-beeb-e564579e41b2)

if you have others solution please tell me.

P/s: if anyone confused why i'm not just use the same color is because i haven't fork this repository yet and i did it on Chrome Devtools

**Comment by muhammadhafijur** [comment]
Hi @moo-light . I think we can ignore this for now. You can also contribute by adding the button hover effect I mentioned for this section.
![Screenshot 2024-10-06 223040](https://github.com/user-attachments/assets/d9556181-4596-4f19-b75a-7b65618bd346)

**Comment by moo-light** [comment]
> Hi @moo-light . I think we can ignore this for now. You can also contribute by adding the button hover effect I mentioned for this section.
> ![Screenshot 2024-10-06 223040](https://github.com/user-attachments/assets/d9556181-4596-4f19-b75a-7b65618bd346)
> 

Alright i will do the other task first

**Comment by muhammadhafijur** [comment]
I have already assigned you this issue in issue #7 . So I'm closing this issue.
