### ISSUE TITLE
Feat: Testimonial Review Section

### ISSUE THREAD

**Issue by Adebesin-Cell** [muhammadhafijur/image-blender#25]
**User Story:**
As a user visiting the **Image Blender** site, it would be great to see reviews from other users in a well-designed testimonial section. This will help build trust and provide feedback on the experiences of others who have used the product.

**Suggested Implementation:**
- Create a **Testimonial Review Section** that showcases user reviews in a responsive grid layout.
- Use a design similar to the testimonial section on the [Nuxt website](https://nuxt.com/), which presents reviews in clean, modern cards with a minimalist design. Each review should include the user's profile picture, name, and the review content.

**Additional Requirements:**
- Create a `db` folder in the root directory with a `userReviews.json` file.
- Create a `userReviews.json` into the testimonial component to dynamically loop over and display the testimonials.
- Ensure the design is fully responsive and aligns with the overall look and feel of the site.

**Comment by Adebesin-Cell** [comment]
Hi @muhammadhafijur,

Can you please assign this issue to me? I’d like to work on creating the **Testimonial Review Section**.

Looking forward to your confirmation!

Thanks in advance!

**Comment by muhammadhafijur** [comment]
Done 🎉

**Comment by Adebesin-Cell** [comment]
Thank you 👍
