### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by KavyaBS123** [muhammadhafijur/image-blender#8]
Hey @muhammadhafijur the header is missing it can be made still better by adding still more info.

**Comment by muhammadhafijur** [comment]
Hi @KavyaBS123 . I’ve tried to keep it minimal and clean. If you have any specific details in mind, feel free to share them. Also, there are [good first issue](https://github.com/muhammadhafijur/image-blender/issues/9) tags on the issue list. If you’d like to add small interactivity, like hover effects and small animations, you’re welcome to contribute! If you need any help. Do let me know.

**Comment by KavyaBS123** [comment]
Hey, I would like to work on such issues, can you please assign me.

**Comment by muhammadhafijur** [comment]
We need to enhance the user experience by implementing an active state for these two buttons. When the buttons are in the active state, they should visually respond to user interactions.

You can use tailwindcss `active:` class for this. With some transition, it will look good. 

Would you like to work on this?

![Screenshot 2024-10-07 151827](https://github.com/user-attachments/assets/7a55539a-480c-43ce-b83b-3fd1c3bc7d82)
