### ISSUE TITLE
Linkedin icon color adjustment for Dark Mode

### ISSUE THREAD

**Issue by muhammadhafijur** [muhammadhafijur/image-blender#9]
The task is to adjust the icon color to match the design standards for dark mode. The LinkedIn icon color should be white by default in dark mode

![Screenshot 2024-10-06 182413](https://github.com/user-attachments/assets/a0ed2ede-ebc4-458a-a04c-31f3465562af)

**Comment by Kriishna1** [comment]
please assign me this.

**Comment by sujalcharati** [comment]
please can i be assigned for this under hacktoberfest

**Comment by muhammadhafijur** [comment]
Since @Kriishna1 requested this first, I’m assigning this task to him. @sujalcharati , I’m assigning you a similar issue as well.

**Comment by muhammadhafijur** [comment]
@sujalcharati you can contribute on this [issue](https://github.com/muhammadhafijur/image-blender/issues/10)
